# Generated by Django 4.2.9 on 2024-01-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=286)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='projects_images/')),
                ('repository', models.URLField()),
                ('skills', models.ManyToManyField(to='content.skill')),
            ],
        ),
    ]
