# Generated by Django 4.2.9 on 2024-01-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=160)),
                ('period', models.CharField(max_length=128)),
                ('skill', models.ManyToManyField(to='content.skill')),
            ],
        ),
    ]
